### ISSUE TITLE
hawthorn.1-2.6.0: Javascript errors on instructor dashboard

### ISSUE THREAD

**Issue by rmoch** [openfun/openedx-docker#105]
## Expected Behavior

LMS Instructor dashboard should allow asynchronous generation of CSV files and download

## Actual Behavior

The page crashes, with javascript errors probably related to incomplete build

## Steps to Reproduce

1. Set `LMS` settings to 
```
    FEATURES["ENABLE_GRADE_DOWNLOADS"] = True
    FEATURES["ALLOW_COURSE_STAFF_GRADE_DOWNLOADS"] = True  
    FEATURES["ENABLE_ASYNC_ANSWER_DISTRIBUTION"] = False
    FEATURES["ENABLE_INSTRUCTOR_BACKGROUND_TASKS"] = False
```
2. import demo course
3. login as instructor to LMS
4. go to `/courses/course-v1:edX+DemoX+Demo_Course/instructor#view-data_download` 
5. click on `Download profile inforamtion as CSV`
6. a request to `/instructor/api/get_students_features/csv` should be POSTed

## Specifications

- Version: hawthorn.1-2.6.0

`oee` image works fine (despite they are some JS errors as well)

**Comment by rmoch** [comment]
![Capture d’écran 2019-05-10 à 10 16 01](https://user-images.githubusercontent.com/89626/57512707-b7163b00-730c-11e9-8432-bd0fdba0b611.png)

**Comment by jmaupetit** [comment]
This bug seems to only occur when `DEBUG` is set to `True`.

**Comment by rmoch** [comment]
Indeed, this trace do not show up when DEBUG is set to False, but the page is still broken. I updated steps to reproduce

**Comment by jmaupetit** [comment]
@rmoch is this issue still relevant?
