### ISSUE TITLE
Control access to instructor CSV files

### ISSUE THREAD

**Issue by rmoch** [openfun/openedx-docker#106]
## Expected Behavior

Instructor CSV export files should only be accessible to instructors of the given course

## Actual Behavior

edX default configuration allows any user knowing the url to download files from filesystem or s3.
Also the url is not difficult to guess. This is a major security flaw.

## Proposal

Add to Fonzie an API endpoint to control user authorization to access requested file then serve it with Nginx using X-Accel-Redirect header.

We will then configure edx-platform to download files from API endpoint instead of Nginx location

```
GRADES_DOWNLOAD = {
   "STORAGE_CLASS": "django.core.files.storage.FileSystemStorage",
   "STORAGE_KWARGS": {
       "location": "/edx/var/edxapp/media/export",  # mountpoint where files will be stored in openedx-docker container
       "base_url": "/api/v1.0/protected/instructor_file",  # URL to access them
   }
}
```

And use Nginx to serve `export` internally.

```
location ~ ^/protected/(?P<file>.*) {
  root /data/media/export;
  try_files /$file =404;
  internal;
}
```

**Comment by jmaupetit** [comment]
With your proposal, Fonzie becomes a _de facto_ requirement. I think you should declare this issue in Fonzie's repository instead and only document implemented feature here.

**Comment by jmaupetit** [comment]
Closing this as it as already been implemented in `oee/hawthorn.1`.
