### ISSUE TITLE
[create-symlinks] Error 1

### ISSUE THREAD

**Issue by dbritos** [openfun/openedx-docker#107]
## Expected Behavior

Description...

## Actual Behavior

dbritos@HP:~/openedx-docker$ make dev-assets
bash -c "mkdir -p data/{static/production,static/development,media,store}"
UID=1000 GID=1000 docker-compose run --rm -e HOME="/tmp" --no-deps lms-dev bash -c "\
	rm -f /edx/app/edxapp/edx-platform/lms/envs/fun && \
	rm -f /edx/app/edxapp/edx-platform/cms/envs/fun && \
	ln -sf /config/lms /edx/app/edxapp/edx-platform/lms/envs/fun && \
	ln -sf /config/cms /edx/app/edxapp/edx-platform/cms/envs/fun"
ln: failed to create symbolic link '/edx/app/edxapp/edx-platform/lms/envs/fun': No such file or directory
Makefile:42: recipe for target 'create-symlinks' failed
make: *** [create-symlinks] Error 1
Description...

When i follow the steps in "https://github.com/openfun/openedx-docker" and type "make dev-assets"  i receive "make: *** [create-symlinks] Error 1"

I run Ubuntu 18.04  and docker
dbritos@HP:~/openedx-docker$ docker -v
Docker version 18.09.5, build e8ff056

## Steps to Reproduce

Description...

1. item 1...
2. item 2...

## Specifications
Ubuntu 18.04  
Docker version 18.09.5, build e8ff056
- Version: ...
- Platform: ...

**Comment by jmaupetit** [comment]
Hi @dbritos! That's odd which branch did you checked out and what is the latest commit sha1?

**Comment by jmaupetit** [comment]
I'll close this issue. Do not hesitate to ask us to re-open it if you are still stucked @dbritos.
