### ISSUE TITLE
Add changelog to OEE branch

### ISSUE THREAD

**Issue by rmoch** [openfun/openedx-docker#110]
## Expected Behavior

We should log our changes to openedx-docker images but also
to edX original edx-platform behavior (xblocks, fonzie)

## Solution

Add a CHANGELOG.md file and complete with all significant changes we made
Add related CI step

see: https://github.com/openfun/fonzie/blob/master/CHANGELOG.md

**Comment by jmaupetit** [comment]
Fixed in #112
