### ISSUE TITLE
[Errno 2] No such file or directory: Path(u'/edx/app/edxapp/edx-demo-course/course.xml')

### ISSUE THREAD

**Issue by TinDang97** [openfun/openedx-docker#115]
**Hi Openfun,
Can you help me fix it? I don't know how to solve this problem.**
Thank you very much!
```
Importing...
    data_dir=/edx/var/edxapp/data, source_dirs=['/edx/app/edxapp/edx-demo-course']
    Importing static content? True
    Importing python lib? True
2019-09-16 05:27:22,212 ERROR 1 [xmodule.modulestore.xml] xml.py:407 - ERROR: Failed to load courselike '/edx/app/edxapp/edx-demo-course': [Errno 2] No such file or directory: Path(u'/edx/app/edxapp/edx-demo-course/course.xml')
Traceback (most recent call last):
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/xml.py", line 402, in try_load_course
    course_descriptor = self.load_course(course_dir, course_ids, errorlog.tracker, target_course_id)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/xml.py", line 463, in load_course
    with open(self.data_dir / course_dir / self.parent_xml) as course_file:
IOError: [Errno 2] No such file or directory: Path(u'/edx/app/edxapp/edx-demo-course/course.xml')
[variant:cms][xmodule.modulestore.xml][env:sandbox] ERROR [b5371ce2c564  1] [xml.py:407] - ERROR: Failed to load courselike '/edx/app/edxapp/edx-demo-course': [Errno 2] No such file or directory: Path(u'/edx/app/edxapp/edx-demo-course/course.xml')
Traceback (most recent call last):
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/xml.py", line 402, in try_load_course
    course_descriptor = self.load_course(course_dir, course_ids, errorlog.tracker, target_course_id)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/xml.py", line 463, in load_course
    with open(self.data_dir / course_dir / self.parent_xml) as course_file:
IOError: [Errno 2] No such file or directory: Path(u'/edx/app/edxapp/edx-demo-course/course.xml')


```

**Comment by jmaupetit** [comment]
Hi @TinDang97 ! Thanks for the report. Can you share more context with us? 

1. Which release are you working on?
2. Which command did you run that generates this error?

**Comment by TinDang97** [comment]
> Hi @TinDang97 ! Thanks for the report. Can you share more context with us?
> 
> 1. Which release are you working on?
> 2. Which command did you run that generates this error?

Hi @jmaupetit ! 
I tried both 2 option hawthorn/1/bare and hawthorn/1/oee.
After that I run "sudo make bootstrap".
Finally, the error is the same with them.

Note: I use "sudo" because docker was installed on root.

**Comment by jmaupetit** [comment]
Can you list files and permissions in the `releases/hawthorn/1/bare/src` directory and paste it here please?

**Comment by jmaupetit** [comment]
Hi @TinDang97 :wave: Have you tried to bootstrap the project recently? We've strongly improved many things to make it easier to use!

**Comment by TinDang97** [comment]
> Hi @TinDang97  Have you tried to bootstrap the project recently? We've strongly improved many things to make it easier to use!

Sorry, 
I was busy some days ago. I will give you know after I try to deploy it again.
Have a nice day :dancer: :dancer:

**Comment by rmoch** [comment]
For the record, this error may happens when attempting to import an empty folder, `course.xml` being the root file of a course archive.
