### ISSUE TITLE
Improve PROFILE_IMAGE_SECRET_KEY default value

### ISSUE THREAD

**Issue by rmoch** [openfun/openedx-docker#118]
## Expected Behavior
User should be able to upload profile image on its profile page http://site/u/username

## Actual Behavior

upload fails because setting PROFILE_IMAGE_SECRET_KEY is not set
    
    File "/edx/app/edxapp/edxplatform/openedx/core/djangoapps/user_api/accounts/image_helpers.py", line 42, in _make_profile_image_name
    return hashlib.md5(settings.PROFILE_IMAGE_SECRET_KEY + username).hexdigest()
    TypeError: unsupported operand type(s) for +: 'NoneType' and 'unicode'

**Comment by rmoch** [comment]
now fixed

**Comment by jmaupetit** [comment]
> now fixed

Where? Can you point the commit / PR that fix this please?

**Comment by rmoch** [comment]
I think here 07e3a142b9ee9afe1cbd16a7c088b91d2f42f09d
