### ISSUE TITLE
[dogwood/3/fun] Allow customizing the CELERY_RESULT_BACKEND setting

### ISSUE THREAD

**Issue by sampaccoud** [openfun/openedx-docker#142]
## Expected Behavior
In dogwood/3/fun, we are trying to set the `CELERY_RESULT_BACKEND` setting to use the database as a result backend : https://github.com/openfun/openedx-docker/blob/master/releases/dogwood/3/fun/config/lms/settings.yml#L81

## Actual Behavior
Actually, in the lms & cms `docker_run_production.py` file, `CELERY_RESULT_BACKEND` is not made configurable.

## Solution

Use our `config` helper to set a default value for the `CELERY_RESULT_BACKEND` setting and make it configurable.

**Comment by rmoch** [comment]
done here f026d54e2a240b208c4a44bef66f07a22e473b4c
