### ISSUE TITLE
Improve user experience when trying to build/run the project with a root user

### ISSUE THREAD

**Issue by sampaccoud** [openfun/openedx-docker#204]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
The `make bootstrap` command fails when launched via a root user or with sudo. We need to fail early, nicely and explain what is the problem of running Docker with a root user instead of failing with a difficult error after screwing up the user's file system.

See this discussion for details: https://github.com/openfun/openedx-docker/issues/203

**Describe the solution you'd like**
Any make command should start by checking that the user does not have the `0` id with:
```bash
id -u
```

**Describe alternatives you've considered**
An alternative could be to modify the Dockerfile to allow building it with a root user.
In this case we can still display a warning but let the user continue if s.he knows what s.he is doing.

**Comment by jmaupetit** [comment]
I would prefer the alternative solution and not enforcing to run commands without using the root user (or sudo). The warning message should be explicit enough so that our users are aware of the potential risk they encounter.
