### ISSUE TITLE
ImportError: No module named proj.settings

### ISSUE THREAD

**Issue by SamuelMarks** [openfun/openedx-docker#259]
Working with `releases/eucalyptus/3/bare`. Can you send through the entire folder it expects? - I'm sure I can figure out the settings it needs from there, but I'd rather not need to reverse-engineer the entire thing…

**Comment by sampaccoud** [comment]
@SamuelMarks sorry I didn't understand your question. I have no knowledge of a "proj" module in openedx-docker. Is it something you introduced on your side?

**Comment by SamuelMarks** [comment]
🤔, I don't believe so, this is all my code: https://github.com/offscale/offregister-openedx/blob/master/offregister_openedx/ubuntu/fun_bare.py (Fabric is basically SSH in Python*)

*technically paramiko is the SSH implementation, and Fabric is a higher level API atop

How does openedx-docker configure Open edX? - Where are the various config files placed? - Do you just use the regular JSON files in the normal locations, or is there extra goings on?

**Comment by sampaccoud** [comment]
@SamuelMarks configuration in [OpenEdX Docker](https://github.com/openfun/openedx-docker) does not use json files. It uses yaml.
If you take for example the ironwood image, the yaml files located in the [config folder](https://github.com/openfun/openedx-docker/tree/master/releases/ironwood/2/bare/config) are parsed via a [small util](https://github.com/openfun/openedx-docker/blob/master/releases/ironwood/2/bare/config/lms/utils.py) and injected in a standard [Django settings file](https://github.com/openfun/openedx-docker/blob/master/releases/ironwood/2/bare/config/lms/docker_run_production.py).

Configuring management on OpenEdX is not trivial. Maybe taking a look at how it's done in [Arnold](https://github.com/openfun/arnold) will help you.

**Comment by sampaccoud** [comment]
Closing this issue as it is not directly related to an issue in this repository.
