### ISSUE TITLE
Cannot build dogwood/3/fun image: "ImportError: cannot import name resolve_url"

### ISSUE THREAD

**Issue by regisb** [openfun/openedx-docker#270]
## Expected Behavior

I expect the dogwood/3/fun image to build correctly.  

## Actual Behavior

Image build fails during asset collection.

## Steps to Reproduce

I ran the following commands:

```
$ ./bin/activate
# (select dogwood/3/fun)
$ . ./bin/../releases/dogwood/3/fun/activate
$ make bootstrap
...
Step 51/51 : RUN NO_PREREQ_INSTALL=1     paver update_assets --settings=fun.docker_build_production --skip-collect
 ---> Running in 6f92e3749cad
Warning: could not find environment JSON file at '/edx/app/lms.env.json'
/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py:14: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support 
for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import utils, x509
---> pavelib.assets.update_assets
---> pavelib.prereqs.install_ruby_prereqs
NO_PREREQ_INSTALL is set, not installing prereqs
---> pavelib.prereqs.install_node_prereqs
NO_PREREQ_INSTALL is set, not installing prereqs
python manage.py lms --settings=fun.docker_build_production preprocess_assets lms/static/sass/*.scss lms/static/themed_sass
Traceback (most recent call last):
  File "manage.py", line 112, in <module>
    startup.run()
  File "/edx/app/edxapp/edx-platform/lms/startup.py", line 34, in run
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 119, in create
    import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/src/django-oauth2-provider/provider/oauth2/__init__.py", line 5, in <module>
    import urls
  File "/usr/local/src/django-oauth2-provider/provider/oauth2/urls.py", line 36, in <module>
    from django.contrib.auth.decorators import login_required
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 6, in <module>
    from django.shortcuts import resolve_url
ImportError: cannot import name resolve_url
```

## Specifications

- Version: https://github.com/openfun/openedx-docker/commit/cf545ea
- Platform: Ubuntu 18.04

```
➭ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

I expect to investigate the root cause, but I am creating this Github issue in the hope that someone has already resolved it. Please check my notes below while I investigate the problem.

**Comment by regisb** [comment]
The /usr/local/lib/python2.7/dist-packages/django/ folder contains both a `shortcuts` folder and a `shortcuts.py` module, which is weird. The `shortcuts/__init__.py` module _does not_ contain a definition for `resolve_url`. However, the `shortcuts.py` module does.

`pip freeze` indicates that Django==1.8.12 is installed, which is consistent with the following command in the Dockerfile:

```
RUN pip install \
      astroid==1.6.0 \
      django==1.8.12 \
      pip==9.0.3 \
      splinter==0.13.0
```

However, the /usr/local/lib/python2.7/dist-packages/django/__init__.py module has:

```
VERSION = (1, 4, 22, 'final', 0)
```

It appears that django==1.4.22 is installed in the same location as django==1.8.12, but without removing the other files.

Django==1.4.22 is installed as part of the `RUN pip install --src /usr/local/src -r requirements/edx/github.txt` step.

**Comment by regisb** [comment]
django-wiki is the culprit:

```
root@3da87febae73:/edx/app/edxapp/edx-platform# pip install --src /usr/local/src -r requirements/edx/github.txt
...
Collecting Django<1.5,>=1.4 (from django-wiki==0.0.5.1->-r requirements/edx/github.txt (line 48))
  Downloading https://files.pythonhosted.org/packages/46/7f/cead60a10b0208451c42e80db2cc90564cf810148ee46631699ec691cbea/Django-1.4.22.tar.gz (7.8MB)
...
```

**Comment by regisb** [comment]
After installing django-wiki, the `shortcuts.py` module is no longer present. This means that the 1.4.22 and the 1.8.12 installation get mangled after the `pip install --src /usr/local/src -r requirements/edx/github.txt` step.

**Comment by regisb** [comment]
At this point, I think there are two options:

1. Patch openfun's fork of [django-wiki](https://github.com/openfun/django-wiki) to depend on `django>=1.4,<1.9`.
2. Manually upgrade django from 1.4.22 to 1.8.12 after the github requirement installation step.

Given that the django-wiki has been untouched for six years, I would recommend option 2. If you agree I can open a PR.

**Comment by jmaupetit** [comment]
Are you sure that django-wiki in this version is not broken when installed with Django 1.8.12?

**Comment by jmaupetit** [comment]
If this is the case, IMO our best option is to pin Django to 1.8.21 in [`fun/requirements.txt`](https://github.com/openfun/openedx-docker/blob/master/releases/dogwood/3/fun/requirements.txt) as it's the latest installed requirement file.

**Comment by regisb** [comment]
> Are you sure that django-wiki in this version is not broken when installed with Django 1.8.12?

Absolutely not :-/ But I assume that 1.8.12 is the version currently running on FUN? If yes, and if you haven encountered issues with django-wiki, then I'd say that both packages are compatible?

> If this is the case, IMO our best option is to pin Django to 1.8.21 in fun/requirements.txt as it's the latest installed requirement file. WDYT?

Django is already pinned to 1.8.12 by requirements/edx/base.txt:

```
root@cb5905e984fb:/edx/app/edxapp/edx-platform# grep -R django== requirements/
requirements/edx/base.txt:django==1.8.12
```

Also, the real issue here is the fact that 1.4.22 somehow steps over the feet of 1.8.12, not the fact 1.8.12 is missing.

**Comment by jmaupetit** [comment]
Even if it's already pinned in a requirement file that is installed earlier, by forcing an upgrade in a later installed requirement file, you will restore the expected Django release, _i.e._ `1.8.12`. The dependency tree is resolved when installing a dependency not globally given already installed dependencies right?

**Comment by regisb** [comment]
> Even if it's already pinned in a requirement file that is installed earlier, by forcing an upgrade in a later installed requirement file, you will restore the expected Django release, i.e. 1.8.12.

In theory, yes. In practice, I observe that 1.8.12 is installed on top of 1.4.22 and that the modules from 1.4.22 are not deleted, thus causing the error message above. This might be an issue with the pip version... or with something else. The underlying root cause is unknown to me.

Note that the solution that you are suggesting is already in place. The Dockerfile contains the following steps:

```
RUN pip install \
      astroid==1.6.0 \
      django==1.8.12 \     <------- install 1.8.12
      pip==9.0.3 \
      splinter==0.13.0
RUN pip install --src /usr/local/src -r requirements/edx/github.txt      <------- install 1.4.22
RUN pip install -r requirements/edx/base.txt      <------- install 1.8.12
```

So in theory 1.8.12 should be replacing 1.4.22. In practice, the `django/shortcuts/__init__.py` file remains there, next to `django/shortcuts.py`.

**Comment by jmaupetit** [comment]
What if you force uninstall Django between the two last steps?

```Dockerfile
RUN pip install --src /usr/local/src -r requirements/edx/github.txt
RUN pip uninstall Django
RUN pip install -r requirements/edx/base.txt
```

**Comment by regisb** [comment]
> What if you force uninstall Django between the two last steps?

Yes, this will work, just like the manual upgrade mentioned in option 2 [above](https://github.com/openfun/openedx-docker/issues/270#issuecomment-747600892). The approach I suggest is (IMHO) a bit simpler:

```
...
RUN pip install \
      astroid==1.6.0 \
      pip==9.0.3 \
      # don't install django here
      splinter==0.13.0
RUN pip install --src /usr/local/src -r requirements/edx/github.txt   # install django==1.4.22 here
RUN pip install --upgrade Django==1.8.12    # upgrade django here
RUN pip install -r requirements/edx/base.txt
...
```

**Comment by jmaupetit** [comment]
I thought uninstalling Django would perform a clean up that is not handled when upgrading from 1.4.22 to 1.8.12 (as you seemed to suggest).

**Comment by regisb** [comment]
Yes, that would work, and is actually simpler. Would you like me to open a PR?

**Comment by jmaupetit** [comment]
If the build is broken, yeah sure! :pray:

**Comment by jmaupetit** [comment]
As it's a bit tricky, feel free to add a comment (and eventually link to this issue?). Thanks!

**Comment by regisb** [comment]
:ok_hand: 

(note that I've had to fork from a different organization. Otherwise I would have lost the redirect from https://github.com/regisb/openedx-docker to https://github.com/overhangio/tutor)
