### ISSUE TITLE
Failed to solve: failed to compute cache key: failed to calculate checksum of ref 

### ISSUE THREAD

**Issue by dylanngo95** [openfun/openedx-docker#328]
## Expected Behavior

Can not run completed bootstrap command.

## Actual Behavior

We got issues with the download library.

## Steps to Reproduce

1. make bootstrap

## Specifications

 > [edxapp 5/8] COPY --from=downloads /downloads/edx-platform-* .:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref zp2wh8029gbqt1357kbr6hdhz::i1p0qru1gizriupvnxy4bzah1: "/downloads/edx-platform-open-release-ironwood.2/node_modules/edx-pattern-library/pattern-library/fonts": not found
make: *** [build] Error 17

Screenshot 2023-06-16 at 3.13.04 PM

**Comment by CABA1998** [comment]
I am having the same error :(
