### ISSUE TITLE
Failed to deploy using docker-compose up due to old node version

### ISSUE THREAD

**Issue by devaziz0** [openfun/openedx-docker#86]
## Expected Behavior
Easy deployment using docker compose up
I have cloned the repo, and executed a docker-compose up

## Actual Behavior
Failed due to old nodejs version
![screenshot from 2018-12-25 12-56-14](https://user-images.githubusercontent.com/26504006/50421933-dd977600-0844-11e9-905d-bccbfde80f2e.png)

## Steps to Reproduce
git clone https://github.com/openfun/openedx-docker
cd openedx-docker
docker-compose up

**Comment by jmaupetit** [comment]
Hi @devaziz0! Thanks for the report. Your screenshot does not trace a failure but warnings. I invite you to test the bootstrap procedure described in the project documentation https://github.com/openfun/openedx-docker#getting-started

If something goes wrong, feel free to add more details in this thread.

**Comment by devaziz0** [comment]
thank you, i was using ubuntu 18.04 which was the wrong version
